apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador
  namespace: demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-reader
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-reader-binding
subjects:
  - kind: ServiceAccount
    name: ambassador
    namespace: demo
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ambassador
  template:
    metadata:
      labels:
        app: ambassador
    spec:
      serviceAccountName: ambassador
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: set-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65535"]
      containers:
        - name: ambassador
          image: datawire/ambassador:2.0
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
